project:
  type: website
  output-dir: "docs"

website:
  title: "«Другая Роза» на сайте proza.ru"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: О Розе
      - href: data.qmd
        text: Данные
      - href: personalities.qmd
        text: Герои
      - href: research.qmd
        text: Исследования
      - href: texts.qmd
        text: Тексты

format:
  html:
    theme: 
    # - lumen
     - journal
    # - custom.scss
    fontsize: "14pt"
    fontcolor: "#555555"
    toc: true
    toc-location: left
    toc-title: Страницы
    page-layout: full
    df-print: paged
    grid:
      sidebar-width: 250px

bibliography: drugaya_roza.bib